#    Classification of family memebers using CNN

#### In this data set i used my family memberspic to classify the diffrent members 
there are 4 family members i want to classify that is Babu(child),didi(my sister),mom(my mother),sonu(me)
this cnn used two convulation layers 
two maxpooling.
two dense layer with 128,64 as units cvalue 
the accuracy is 93%

In [48]:
import keras
import tensorflow as tf 
from keras.preprocessing.image import ImageDataGenerator 
import cv2

In [14]:
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.layers import Dropout

In [40]:
# the CNN for this model
modelfamily= Sequential()
modelfamily.add(Conv2D(64, (3, 3), input_shape = (64, 64, 3), activation = 'relu'))
modelfamily.add(MaxPooling2D(pool_size = (2, 2)))
modelfamily.add(Conv2D(32, (3, 3), input_shape = (64, 64, 3), activation = 'relu'))
modelfamily.add(MaxPooling2D(pool_size=(3,3)))

In [41]:
# flatten operation after doing convulation
modelfamily.add(Flatten())

In [42]:
# applying deeplearning from the flatten 
modelfamily.add(Dense(units=128,activation='relu'))
modelfamily.add(Dropout(0.2))
modelfamily.add(Dense(units=64,activation='relu'))

In [43]:
# categorical classification for 4 class
modelfamily.add(Dense(units=4,activation='softmax'))

In [44]:
# compile the data value 
modelfamily.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [12]:
# data generation for the model preperation
from keras.preprocessing.image import ImageDataGenerator\
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

training_set = train_datagen.flow_from_directory('D:/machine learning/family image cv',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                class_mode='categorical') # important the class model 



test_datagen = ImageDataGenerator(rescale = 1./255)

test_set = test_datagen.flow_from_directory('D:/machine learning/family image cv1',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'categorical')



model1 = modelfamily.fit_generator(training_set,
                         steps_per_epoch = 30,
                         epochs = 3,
                         validation_data = test_set)


modelfamily.save("family.h5")
print("Saved model to disk")

In [45]:
# testing for the images
import numpy as np
from keras.preprocessing import image
from keras.models import load_model

In [46]:
training_set.class_indices

{'babu': 0, 'did': 1, 'mom': 2, 'sonu': 3}

In [49]:
test_image = image.load_img("D:/phd_for_automobile/IIT Mumbai2020/mypic.jpg", target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
model=load_model("family.h5")
result = model.predict(test_image) 
training_set.class_indices # its giving how many classes are there 
if result[0][0] == 1:
    prediction = 'babu'
    print(prediction)
    
elif result[0][1]==1:
    prediction = 'didi'
    print(prediction)
    
elif result[0][2]==1:
    prediction = 'mom'
    print(prediction)
    
else:
    prediction = 'sonu'
    print(prediction)
result

didi


array([[0., 1., 0., 0.]], dtype=float32)

In [23]:
print(result)

In [25]:
print(modelfamily.summary())


Found 70 images belonging to 4 classes.
Found 37 images belonging to 4 classes.
Epoch 1/3
30/30 [==============================] - 191s 6s/step - loss: 0.5091 - accuracy: 0.7664 - val_loss: 0.4180 - val_accuracy: 0.8311
Epoch 2/3
30/30 [==============================] - 186s 6s/step - loss: 0.2734 - accuracy: 0.8886 - val_loss: 0.1967 - val_accuracy: 0.9054
Epoch 3/3
30/30 [==============================] - 179s 6s/step - loss: 0.1711 - accuracy: 0.9371 - val_loss: 0.1559 - val_accuracy: 0.9595
Saved model to disk


{'babu': 0, 'did': 1, 'mom': 2, 'sonu': 3}

didi


array([[0., 1., 0., 0.]], dtype=float32)

[[0. 0. 1. 0.]]


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 31, 31, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 29, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 9, 9, 32)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 2592)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               331904    
_________________________________________________________________
dense_2 (Dense)              (None, 128)              